Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 36, in <module>
    import cflib.crtp
ImportError: No module named 'cflib'
Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 36, in <module>
    import cflib.crtp
ImportError: No module named 'cflib'
Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 36, in <module>
    import cflib.crtp
ImportError: No module named 'cflib'
Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 36, in <module>
    import cflib.crtp
ImportError: No module named 'cflib'
ERROR:cflib.crazyflie:Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 165, in <module>
    le = LoggingExample("radio://0/81/2M",socket= mySocket)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 65, in __init__
    self._cf.open_link(link_uri)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 244, in open_link
    self.connection_failed.call(link_uri, exception_text)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/utils/callbacks.py", line 54, in call
    cb(*args)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 129, in _connection_failed
    self._socket.close()
AttributeError: 'LoggingExample' object has no attribute '_socket'
ERROR:cflib.crazyflie:Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 165, in <module>
    le = LoggingExample("radio://0/81/2M",socket= mySocket)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 65, in __init__
    self._cf.open_link(link_uri)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 244, in open_link
    self.connection_failed.call(link_uri, exception_text)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/utils/callbacks.py", line 54, in call
    cb(*args)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 129, in _connection_failed
    self._socket.close()
AttributeError: 'LoggingExample' object has no attribute '_socket'
ERROR:cflib.crazyflie:Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 165, in <module>
    le = LoggingExample("radio://0/81/2M",socket= mySocket)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 65, in __init__
    self._cf.open_link(link_uri)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 244, in open_link
    self.connection_failed.call(link_uri, exception_text)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/utils/callbacks.py", line 54, in call
    cb(*args)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 129, in _connection_failed
    self._socket.close()
AttributeError: 'LoggingExample' object has no attribute '_socket'
ERROR:cflib.crazyflie:Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 165, in <module>
    le = LoggingExample("radio://0/81/2M",socket= mySocket)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 65, in __init__
    self._cf.open_link(link_uri)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 244, in open_link
    self.connection_failed.call(link_uri, exception_text)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/utils/callbacks.py", line 54, in call
    cb(*args)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 129, in _connection_failed
    self._socket.close()
AttributeError: 'LoggingExample' object has no attribute '_socket'
ERROR:cflib.crazyflie:Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 165, in <module>
    le = LoggingExample("radio://0/81/2M",socket= mySocket)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 65, in __init__
    self._cf.open_link(link_uri)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 244, in open_link
    self.connection_failed.call(link_uri, exception_text)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/utils/callbacks.py", line 54, in call
    cb(*args)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 129, in _connection_failed
    self._socket.close()
AttributeError: 'LoggingExample' object has no attribute '_socket'
ERROR:cflib.crazyflie:Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 165, in <module>
    le = LoggingExample("radio://0/81/2M",socket= mySocket)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 65, in __init__
    self._cf.open_link(link_uri)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 244, in open_link
    self.connection_failed.call(link_uri, exception_text)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/utils/callbacks.py", line 54, in call
    cb(*args)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 129, in _connection_failed
    self._socket.close()
AttributeError: 'LoggingExample' object has no attribute '_socket'
ERROR:cflib.crazyflie:Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 165, in <module>
    le = LoggingExample("radio://0/81/2M",socket= mySocket)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 65, in __init__
    self._cf.open_link(link_uri)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 244, in open_link
    self.connection_failed.call(link_uri, exception_text)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/utils/callbacks.py", line 54, in call
    cb(*args)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 129, in _connection_failed
    self._socket.close()
AttributeError: 'LoggingExample' object has no attribute '_socket'
ERROR:cflib.crazyflie:Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 165, in <module>
    le = LoggingExample("radio://0/81/2M",socket= mySocket)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 65, in __init__
    self._cf.open_link(link_uri)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 244, in open_link
    self.connection_failed.call(link_uri, exception_text)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/utils/callbacks.py", line 54, in call
    cb(*args)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 129, in _connection_failed
    self._socket.close()
AttributeError: 'LoggingExample' object has no attribute '_socket'
ERROR:cflib.crazyflie:Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 165, in <module>
    le = LoggingExample("radio://0/82/2M",socket= mySocket)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 65, in __init__
    self._cf.open_link(link_uri)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 244, in open_link
    self.connection_failed.call(link_uri, exception_text)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/utils/callbacks.py", line 54, in call
    cb(*args)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 129, in _connection_failed
    self._socket.close()
AttributeError: 'LoggingExample' object has no attribute '_socket'
ERROR:cflib.crazyflie:Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 165, in <module>
    le = LoggingExample("radio://0/82/2M",socket= mySocket)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 65, in __init__
    self._cf.open_link(link_uri)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 244, in open_link
    self.connection_failed.call(link_uri, exception_text)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/utils/callbacks.py", line 54, in call
    cb(*args)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 129, in _connection_failed
    self._socket.close()
AttributeError: 'LoggingExample' object has no attribute '_socket'
ERROR:cflib.crazyflie:Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 165, in <module>
    le = LoggingExample("radio://0/82/2M",socket= mySocket)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 65, in __init__
    self._cf.open_link(link_uri)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 244, in open_link
    self.connection_failed.call(link_uri, exception_text)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/utils/callbacks.py", line 54, in call
    cb(*args)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 129, in _connection_failed
    self._socket.close()
AttributeError: 'LoggingExample' object has no attribute '_socket'
ERROR:cflib.crazyflie:Couldn't load link driver: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 119, in __init__
    device = _find_devices()[devid]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 218, in open_link
    link_uri, self._link_quality_cb, self._link_error_cb)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/__init__.py", line 91, in get_link_driver
    instance.connect(uri, link_quality_callback, link_error_callback)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 188, in connect
    address)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 98, in __init__
    _RadioManager._radios[self._devid] = _SharedRadio(self._devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crtp/radiodriver.py", line 67, in __init__
    self.radio = Crazyradio(devid=devid)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/drivers/crazyradio.py", line 121, in __init__
    raise Exception('Cannot find a Crazyradio Dongle')
Exception: Cannot find a Crazyradio Dongle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 165, in <module>
    le = LoggingExample("radio://0/82/2M",socket= mySocket)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 65, in __init__
    self._cf.open_link(link_uri)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/crazyflie/__init__.py", line 244, in open_link
    self.connection_failed.call(link_uri, exception_text)
  File "/home/taste/miniconda3/envs/cfclient/lib/python3.4/site-packages/cflib/utils/callbacks.py", line 54, in call
    cb(*args)
  File "/home/taste/Documents/FlyingTasters/PythonSocketServer/myBasiclogAndRampWithSocketServerC.py", line 129, in _connection_failed
    self._socket.close()
AttributeError: 'LoggingExample' object has no attribute '_socket'
